# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build Platform Persistence with Maven
      run: mvn -B package --file platform-persistence/pom.xml
    - name: Build Platform Security with Maven
      run: mvn -B package --file platform-security/pom.xml
    - name: Build Platform Merchant
      run: mvn -B package --file platform-merchant/pom.xml
    - name: Build State Machine
      run: mvn -B package --file state-machine/pom.xml
      
